### ISSUE TITLE
OpenAPI/Swagger

### ISSUE THREAD

**Issue by PhearZero** [HospitalRun/hospitalrun-core#1]
## 🚀 Feature Proposal

OpenAPI/Swagger

## Motivation
> Work hard at being lazy ~ Mike Feher

Single Source of truth. SOLID interface between all projects

# Backlog:
- [ ] Generate Core Models (finalize OpenAPI->TS Model Interface)
- [ ] Generate Core Services (Configure Services CodeGen Template)

# Related Issues:
HospitalRun/hospitalrun#12
HospitalRun/hospitalrun#15

**Comment by fox1t** [comment]
Not in scope anymore. We are going to generate Swagger schemas from the code.
