### ISSUE TITLE
Add entities schemas to documentation

### ISSUE THREAD

**Issue by fox1t** [HospitalRun/hospitalrun-core#40]
## 🚀 Feature Proposal

- [x] extract all of the schema of the old entities
- [ ] Update every doc accordingly to our new needs

**Comment by tehKapa** [comment]
> Do you have any suggestions on what is the correct path of mapping the schemas?
I was thinking about this:
1. open <http://demo.hospitalrun.io|demo.hospitalrun.io> as admin user
2. take not from every section and understand which entities are used
3. open the couchdb of the old version (from the demo) and extract all of the schema of the old entities
4. create 1 doc per old entity
5. update that doc accordingly to our new needs
6. implement every entity using typebox in the core repository
<sub>[View in Slack](https://hospitalrun.slack.com/archives/C014AFL2T0T/p1593595496000300)</sub>

**Comment by tehKapa** [comment]
All schemas can be founds [here](https://github.com/HospitalRun/hospitalrun-core/tree/master/src/design-documents) and [here](https://github.com/HospitalRun/hospitalrun-core/tree/master/src/example-documents/v1)

**Comment by fox1t** [comment]
Done!
